services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    container_name: dexon-timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dexon
    ports:
      - "5432:5432"
    volumes:
      - dexon_timescaledb_data:/var/lib/postgresql/data

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    container_name: dexon-openobserve
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "helloworld"
    ports:
      - "5080:5080"
    volumes:
      - dexon_openobserve_data:/data

volumes:
  dexon_timescaledb_data:
  dexon_openobserve_data:
