CREATE TYPE ORDER_STATUS AS ENUM ('PENDING', 'FILLED', 'CANCELED');
CREATE TYPE ORDER_SIDE AS ENUM ('BUY', 'SELL');
CREATE TYPE ORDER_CONDITION AS ENUM ('LIMIT', 'STOP');

CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    wallet VARCHAR(42),
    from_token VARCHAR(10) NOT NULL,
    to_token VARCHAR(10) NOT NULL,
    status ORDER_STATUS NOT NULL DEFAULT 'PENDING',
    side ORDER_SIDE NOT NULL,
    condition ORDER_CONDITION NOT NULL,
    price NUMERIC(78,18) NOT NULL,
    filled_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE,

    FOREIGN KEY (from_token) REFERENCES tokens(id) ON DELETE CASCADE,
    FOREIGN KEY (to_token) REFERENCES tokens(id) ON DELETE CASCADE
);
